---
- name: Sample playbook
  hosts: all
  tasks:
    - name: Sample task
      ansible.builtin.debug:
        msg: This is the debug from a sample task

    - name: Print /etc/hosts by lookup
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', '/etc/hosts') }}"

    - name: Print /etc/hosts by command
      block:
        - ansible.builtin.command: cat /etc/hosts
          register: hosts_output

        - ansible.builtin.debug:
            var: hosts_output.stdout_lines
